---
- name: compliance check for STIG rules, packages, simplified
  hosts: all

  tasks:
  - name: "RHEL-08-020330 | HIGH | PATCH | RHEL 8 must not have accounts configured with blank or null passwords. | Remove nullok"
    replace:
        path: "{{ item }}"
        regexp: ' nullok'
        replace: ''
    with_items:
        - /etc/pam.d/system-auth
        - /etc/pam.d/password-auth

  - name: "RHEL-08-020330 | HIGH | PATCH | RHEL 8 must not have accounts configured with blank or null passwords. | Set PermitEmptyPasswords to no"
    lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '(?i)^#?PermitEmptyPasswords'
        line: 'PermitEmptyPasswords no'
    
